services:
  sqlserver:
    build:
      context: .
      dockerfile: backend/database/Dockerfile
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "a123456789A!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./initdb:/initdb
    networks: 
      - mynetwork
  
  admin-service:
    build:
      context: ./backend/myshop/admin-service
    container_name: admin-service
    ports:
      - "5001:80"
    depends_on:
      - sqlserver
    networks:
      - mynetwork
  
  catalog-service:
    build:
      context: ./backend/myshop/catalog-service
    container_name: catalog-service
    ports:
      - "5002:80"
    volumes:
      - product_images:/app/public/products
    depends_on:
      - sqlserver
    networks:
      - mynetwork
      
  api-gateway:
    build:
      context: ./backend/myshop/api-gateway
    container_name: api-gateway
    ports:
      - "5000:80"
    depends_on:
      - admin-service
      - catalog-service
    networks:
      - mynetwork
  
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "4200:80"
    volumes:
      - product_images:/usr/share/nginx/html/assets/products
    depends_on:
      - api-gateway
    networks:
      - mynetwork
      
volumes:
  sql_data:
  product_images:
  
networks:
  mynetwork:
    driver: bridge
