version: '3.4'

services:
  user-service:
    image: userservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver_kone;Database=UserDb;User Id=sa;Password=a123456789A!
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022
    environment:
      SA_PASSWORD: "a123456789A!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
